dist: xenial
language: node_js
node_js:
  - stable
cache: yarn
branches:
  only:
    - master
env:
  global:
    - EXPO_DEBUG=true
install:
  - yarn install
  - npm install -g expo-cli
script:
  - yarn eslint
  - yarn test
deploy:
  skip_cleanup: true # avoid to remove node_modules
  provider: script
  script: bash scripts/deploy.sh
